# Generated by Django 5.1.2 on 2024-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("activate_gateway", "Activate Gateway"),
                            ("gateway_token", "Gateway Token"),
                            ("reserve_price", "Reserve Price"),
                            ("terms_content", "Terms Content"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("value", models.TextField(verbose_name="Value")),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
