# Generated by Django 5.1.2 on 2024-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=15, verbose_name="Mobile Number"),
                ),
                (
                    "otp_code",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="OTP Code"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="settings",
            name="type",
            field=models.CharField(
                choices=[
                    ("activate_gateway", "Activate Gateway"),
                    ("gateway_token", "Gateway Token"),
                    ("reserve_price", "Reserve Price"),
                    ("terms_content", "Terms Content"),
                    ("use_redis_cache", "Use Redis Cache"),
                ],
                max_length=16,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
