# Generated by Django 5.1.2 on 2024-11-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                ("month", models.CharField(max_length=32, verbose_name="Month")),
                ("date", models.IntegerField(verbose_name="Date")),
                (
                    "day_of_week",
                    models.CharField(max_length=64, verbose_name="Day of week"),
                ),
                ("time", models.TimeField(verbose_name="Start time")),
                (
                    "first_name",
                    models.CharField(max_length=128, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="Last Name"),
                ),
                (
                    "national_code",
                    models.CharField(max_length=64, verbose_name="National code"),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=64, verbose_name="Mobile number"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_reservs",
                        to="app_doctor.doctor",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
