# Generated by Django 5.1.2 on 2024-12-12 16:10

import django.core.validators
import django.db.models.deletion
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "phone",
                    utils.db.fields.PhoneField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(0?9[0-9]{9})$",
                                message="Invalid Mobile Number Format.",
                            )
                        ],
                        verbose_name="Phone",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(max_length=10, verbose_name="National Code"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("field", models.CharField(max_length=64, verbose_name="Field")),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorDateTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Start time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_times",
                        to="app_doctor.doctor",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor DateTime",
                "verbose_name_plural": "Doctor DateTimes",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("doctor", "date", "time")},
            },
        ),
    ]
